package com.example.myapplicationx.database.model

import android.os.Parcelable
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(
    tableName = "receipts",
    indices = [
        Index(value = ["receipt_number"], unique = true),
        Index(value = ["tenant_id"])
    ],
    foreignKeys = [ForeignKey(
        entity = TenantEntity::class,
        parentColumns = ["tenant_id"],
        childColumns = ["tenant_id"],
        onDelete = ForeignKey.CASCADE
    )]
)
data class ReceiptEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "receipt_id")
    val receiptId: Int = 0,
    
    @ColumnInfo(name = "receipt_number")
    val receiptNumber: String,

    @ColumnInfo(name = "tenant_id")
    val tenantId: Int,

    @ColumnInfo(name = "tenant_name")
    val tenantName: String,

    @ColumnInfo(name = "amount_received")
    val amountReceived: Double,

    @ColumnInfo(name = "receipt_date")
    val receiptDate: String,

    @ColumnInfo(name = "receipt_note")
    val receiptNote: String? = null,

    // Added missing field to resolve parameter errors
    @ColumnInfo(name = "is_auto_generated")
    val isAutoGenerated: Boolean = false,

    @ColumnInfo(name = "is_adjustment")
    val isAdjustment: Boolean = false,
    
    @ColumnInfo(name = "credit_reference")
    val creditReference: String? = null
) : Parcelable