name: Unzip Archive

on:
  workflow_dispatch: # Allows manual triggering in the Actions tab

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip file
        run: unzip -o archive.zip -d .

      - name: Commit unzipped files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Unzip archive.zip" || echo "No changes to commit"
          git push
