name: Move My Applicationx (12) to Root

on:
  workflow_dispatch:
permissions:
  contents: write  
jobs:
  move-to-root:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move all files and folders from My Applicationx (12) to root
        run: |
          SRC="My Applicationx (12)"
          shopt -s dotglob
          if [ -d "$SRC" ]; then
            mv "$SRC"/* ./
            rmdir "$SRC" || true
          else
            echo "Directory '$SRC' does not exist."
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Move all files and folders from 'My Applicationx (12)' to root via Actions" || exit 0
          git push
