name: Move Folders Up

on:
  workflow_dispatch: # Manual trigger
  # You can also schedule or trigger on push if needed

jobs:
  move-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move all folders up from subdir to root
        run: |
          # Set your subdirectory name here
          SUBDIR="subdir"
          # Move only directories (not files) from subdir to root
          shopt -s dotglob
          for dir in "$SUBDIR"/*/; do
            [ -d "$dir" ] && mv "$dir" ./
          done
          # Optionally remove the now empty subdir
          rmdir "$SUBDIR" || true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Move all folders one level up via GitHub Actions" || exit 0
          git push
